# Generated by Django 3.0.7 on 2020-09-01 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financeyear', models.CharField(max_length=45)),
                ('monthly_fee', models.IntegerField()),
                ('education_fee', models.IntegerField()),
                ('penal_interest', models.IntegerField()),
                ('dividend', models.IntegerField()),
                ('due_date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, default=finance.models.increment_receipt_number, max_length=10, null=True)),
                ('date', models.DateField()),
                ('termmonth', models.CharField(max_length=45)),
                ('amt', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
