# Generated by Django 3.0.7 on 2020-09-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_register',
            name='termmonth',
            field=models.CharField(max_length=200),
        ),
    ]
