# Generated by Django 3.0.7 on 2020-09-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='receiptno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
