# Generated by Django 3.0.7 on 2020-09-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_subscription_receiptno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='receiptno',
            field=models.CharField(default='', max_length=10),
        ),
    ]
