# Generated by Django 3.0.7 on 2020-09-01 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='profile_image')),
                ('father_name', models.CharField(max_length=45)),
                ('mother_name', models.CharField(max_length=45)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=45)),
                ('nationality', models.CharField(choices=[('India', 'India'), ('Others', 'Others')], max_length=45)),
                ('gothram', models.CharField(choices=[('gothram1', 'aruventla'), ('gothram2', 'dravida'), ('gothram3', 'test2'), ('gothram4', 'test3'), ('Others', 'Others')], max_length=45)),
                ('subsect', models.CharField(choices=[('subset1', 'value1'), ('subset1', 'value2'), ('subset1', 'value3'), ('subset1', 'value4'), ('Others', 'Others')], max_length=45)),
                ('blood_group', models.CharField(choices=[('a+', 'A+'), ('o+', 'O+'), ('b+', 'B+'), ('ab+', 'AB+'), ('a-', 'A-'), ('o-', 'O-'), ('b-', 'B-'), ('ab-', 'AB-')], max_length=5)),
                ('phone_no', models.CharField(max_length=11, unique=True)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('single', 'Single')], max_length=10)),
                ('job', models.CharField(choices=[('private', 'Private'), ('govt', 'GovtEmployee'), ('student', 'Student'), ('business', 'Business'), ('housewife', 'House Wife')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('monthsub_paiddate', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
