# Generated by Django 3.0.7 on 2020-09-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='monthsub_paiddate',
            field=models.DateField(),
        ),
    ]
