# Generated by Django 3.0.7 on 2020-09-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberprofile', '0002_auto_20200901_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='monthsub_paiddate',
            field=models.DateField(null=True),
        ),
    ]
